### ISSUE TITLE
support HUnit > 1.4.0.0

### ISSUE THREAD

**Issue by juhp** [mtesseract/haskell-partial-order#1]
Hi, it seems partial-order's tests depends on HUnit < 1.4.
However Stackage Nightly currently has 1.5.
Any chance of supporting newer HUnit?

**Comment by mtesseract** [comment]
Hi,

thanks for your report!

I have upgraded the LTS resolver and added matching version bounds. New package is on hackage and PR for stackage is open.

Thanks!
Moritz

**Comment by juhp** [comment]
Thanks! :+1:
