### ISSUE TITLE
Redundant dependency

### ISSUE THREAD

**Issue by L-TChen** [mtesseract/haskell-partial-order#7]
This package depends on `container` but it is only used to specify that `Set` is an instance of `PartialOrd`. Would it be okay to include a flag in `.cabal` to exclude this dependency optionally?

**Comment by mtesseract** [comment]
Hi!
Thanks for your idea.
Sure, we can do this.
Would you like to open an PR?
I am not sure when I would be able to take care of this.
Best,
Moritz

**Comment by L-TChen** [comment]
Sure, I can do it (when I switch to work on something relevant later).

**Comment by mtesseract** [comment]
merged.
